### ISSUE TITLE
Add indication that the script is running

### ISSUE THREAD

**Issue by haozhun** [tmikov/hermes-explorer-page#2]
Maybe a greyed out run button

**Comment by tmikov** [comment]
There is indication. It says "Running...". Isn't it always visible?

**Comment by haozhun** [comment]
I just checked that. `Running` shows up on Chrome, but not on Firefox. This is probably due to #3.

**Comment by tmikov** [comment]
Introducing a small delay with setTimeout() will probably fix it.

**Comment by tmikov** [comment]
e70d14ecbdf4f6c7df3e60699e39c93875d06eca fixed it by moving Hermes to a web worker.
