### ISSUE TITLE
Avoid locking up UI and show prints as they happen

### ISSUE THREAD

**Issue by haozhun** [tmikov/hermes-explorer-page#3]
Running the following program with `-O` demonstrates the problem.

```
print("line 1");
var sum = 0;
for (var i = 0; i < 10000000; i++) {
  sum += i*i;
}
print("line 6");
```

Fixing this may require finding a way to yield from the Hermes code from time to time. I don't know how easy or hard this is.

This is more of a wish.

**Comment by tmikov** [comment]
The best approach is probably to move the VM to a webworker, which is my longer term goal anyway.

**Comment by tmikov** [comment]
Introducing a small delay with setTimeout() will probably fix it.

**Comment by tmikov** [comment]
e70d14ecbdf4f6c7df3e60699e39c93875d06eca moves Hermes to a web worker, so everything is asynchronous and the UI is no longer blocked. The output is not updated incrementally - I don't think that is really necessary or worthwhile, but if you think so, please open a new issue.
